name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-11, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install linux dependencies
        if: runner.os == 'Linux' 
        run: sudo apt-get install -y ninja-build 

      - uses: secondlife/action-autobuild@v4
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
